title: Registering to use the Twitter API
hero_image: images/banner.png
subtitle: registering-twitter-api subtitle
description: registering-twitter-api description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Register a Twitter app

