title: registering-twitter-api
hero_image: images/banner.png
description: Register to use the Twitter API
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: true
copyedit: false
interests:
technologies: "twitter"
steps:
  - title: Register your app
