---
title: Registra tu aplicación en Twitter
hero_image: images/banner.png
description: Regístrate para usar la API de Twitter
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: true
copyedit: true
interests:
technologies: "twitter"
steps:
  - title: Registra tu aplicación
